
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test
spec:
  selector:
    app: test
    tier: worker
  ports:
  - port: 80
    targetPort: 1337
  type:
    LoadBalancer
  